apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: solutions/helm/techtrends-deployment
    repoURL: https://github.com/amh23/nd064_course_1/tree/main/project/argocd
    targetRevision: HEAD