namespace:
  name: prod

service:
  port: 7111

image:
  repository: amh23/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  memory: 128Mi
  CPU: 350m

limits:
  memory: 256Mi
  CPU: 500m